/*
 * action types
 */
export const CHANGE_COLOR = 'CHANGE_COLOR';
export const REQUEST_COUNTRIES_BY_CONTINENT = 'REQUEST_COUNTRIES_BY_CONTINENT';
export const NEXT_COUNTRY = 'NEXT_COUNTRY';
export const RECEIVE_POSTS = 'RECEIVE_POSTS';
export const LOAD_COURSES_SUCCESS = "LOAD_COURSES_SUCCESS";
export const LOAD_AUTHORS_SUCCESS = "LOAD_AUTHORS_SUCCESS";
